//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightBulb.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LightBulb.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT.
        /// </summary>
        public static string ABOUT {
            get {
                return ResourceManager.GetString("ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_Menu {
            get {
                return ResourceManager.GetString("About_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and ends at.
        /// </summary>
        public static string and_ends_at {
            get {
                return ResourceManager.GetString("and_ends_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application whitelist.
        /// </summary>
        public static string Application_whitelist {
            get {
                return ResourceManager.GetString("Application_whitelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-update.
        /// </summary>
        public static string Auto_update {
            get {
                return ResourceManager.GetString("Auto_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to detect location automatically based on your IP.
        /// </summary>
        public static string Autodetect_ToolTip {
            get {
                return ResourceManager.GetString("Autodetect_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness offset:.
        /// </summary>
        public static string Brightness_offset {
            get {
                return ResourceManager.GetString("Brightness_offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness offset ↓.
        /// </summary>
        public static string Brightness_offset_down {
            get {
                return ResourceManager.GetString("Brightness_offset_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global hotkey to decrease current brightness offset.
        /// </summary>
        public static string Brightness_offset_down_ToolTip {
            get {
                return ResourceManager.GetString("Brightness_offset_down_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness offset ↑.
        /// </summary>
        public static string Brightness_offset_up {
            get {
                return ResourceManager.GetString("Brightness_offset_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global hotkey to increase current brightness offset.
        /// </summary>
        public static string Brightness_offset_up_ToolTip {
            get {
                return ResourceManager.GetString("Brightness_offset_up_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to reset.
        /// </summary>
        public static string Click_to_reset {
            get {
                return ResourceManager.GetString("Click_to_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color temperature during the day.
        /// </summary>
        public static string Color_temperature_during_the_day {
            get {
                return ResourceManager.GetString("Color_temperature_during_the_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color temperature during the night.
        /// </summary>
        public static string Color_temperature_during_the_night {
            get {
                return ResourceManager.GetString("Color_temperature_during_the_night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current temperature and brightness values are adjusted by an offset:.
        /// </summary>
        public static string Current_temperature_and_brightness_values_are_adjusted_by_an_offset {
            get {
                return ResourceManager.GetString("Current_temperature_and_brightness_values_are_adjusted_by_an_offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 day.
        /// </summary>
        public static string day_1 {
            get {
                return ResourceManager.GetString("day_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness during the day.
        /// </summary>
        public static string Day_brightness_ToolTip1 {
            get {
                return ResourceManager.GetString("Day_brightness_ToolTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note that this brightness setting applies to the color gamma, not to the actual brightness of the monitor..
        /// </summary>
        public static string Day_brightness_ToolTip2 {
            get {
                return ResourceManager.GetString("Day_brightness_ToolTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your computer is already capable of auto-adjusting screen brightness based on lighting conditions (common for laptops), it&apos;s recommended to disable LightBulb&apos;s brightness control by keeping both brightness settings at 100%..
        /// </summary>
        public static string Day_brightness_ToolTip3 {
            get {
                return ResourceManager.GetString("Day_brightness_ToolTip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day-time brightness:.
        /// </summary>
        public static string Day_time_brightness {
            get {
                return ResourceManager.GetString("Day_time_brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day-time color temperature:.
        /// </summary>
        public static string Day_time_color_temperature {
            get {
                return ResourceManager.GetString("Day_time_color_temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default to day-time configuration.
        /// </summary>
        public static string Default_to_day_time_configuration {
            get {
                return ResourceManager.GetString("Default_to_day_time_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable for....
        /// </summary>
        public static string Disable_for {
            get {
                return ResourceManager.GetString("Disable_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamma polling.
        /// </summary>
        public static string Gamma_polling {
            get {
                return ResourceManager.GetString("Gamma_polling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamma smoothing.
        /// </summary>
        public static string Gamma_smoothing {
            get {
                return ResourceManager.GetString("Gamma_smoothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour.
        /// </summary>
        public static string hour_1 {
            get {
                return ResourceManager.GetString("hour_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 hours.
        /// </summary>
        public static string hours_12 {
            get {
                return ResourceManager.GetString("hours_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 hours.
        /// </summary>
        public static string hours_3 {
            get {
                return ResourceManager.GetString("hours_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 hours.
        /// </summary>
        public static string hours_6 {
            get {
                return ResourceManager.GetString("hours_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location-based.
        /// </summary>
        public static string Location_based {
            get {
                return ResourceManager.GetString("Location_based", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error resolving location.
        /// </summary>
        public static string Location_error {
            get {
                return ResourceManager.GetString("Location_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can enter coordinates directly or specify a search query.
        /// </summary>
        public static string Location_query_ToolTip1 {
            get {
                return ResourceManager.GetString("Location_query_ToolTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples of valid values:.
        /// </summary>
        public static string Location_query_ToolTip2 {
            get {
                return ResourceManager.GetString("Location_query_ToolTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Location_query_ToolTip3 {
            get {
                return ResourceManager.GetString("Location_query_ToolTip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Location_query_ToolTip4 {
            get {
                return ResourceManager.GetString("Location_query_ToolTip4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure sunrise and sunset manually.
        /// </summary>
        public static string Manual_ToolTip {
            get {
                return ResourceManager.GetString("Manual_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 minute.
        /// </summary>
        public static string minute_1 {
            get {
                return ResourceManager.GetString("minute_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 minutes.
        /// </summary>
        public static string minutes_30 {
            get {
                return ResourceManager.GetString("minutes_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 minutes.
        /// </summary>
        public static string minutes_5 {
            get {
                return ResourceManager.GetString("minutes_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness during the night.
        /// </summary>
        public static string Night_brightness_ToolTip1 {
            get {
                return ResourceManager.GetString("Night_brightness_ToolTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note that this brightness setting applies to the color gamma, not to the actual brightness of the monitor..
        /// </summary>
        public static string Night_brightness_ToolTip2 {
            get {
                return ResourceManager.GetString("Night_brightness_ToolTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your computer is already capable of auto-adjusting screen brightness based on lighting conditions (common for laptops), it&apos;s recommended to disable LightBulb&apos;s brightness control by keeping both brightness settings at 100%..
        /// </summary>
        public static string Night_brightness_ToolTip3 {
            get {
                return ResourceManager.GetString("Night_brightness_ToolTip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night-time color temperature:.
        /// </summary>
        public static string Night_time_color_temperature {
            get {
                return ResourceManager.GetString("Night_time_color_temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to offset.
        /// </summary>
        public static string offset {
            get {
                return ResourceManager.GetString("offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause when fullscreen.
        /// </summary>
        public static string Pause_when_fullscreen {
            get {
                return ResourceManager.GetString("Pause_when_fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREVIEW.
        /// </summary>
        public static string PREVIEW {
            get {
                return ResourceManager.GetString("PREVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh the list of available applications.
        /// </summary>
        public static string Refresh_the_list_of_available_applications {
            get {
                return ResourceManager.GetString("Refresh_the_list_of_available_applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESET.
        /// </summary>
        public static string RESET {
            get {
                return ResourceManager.GetString("RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset offset.
        /// </summary>
        public static string Reset_offset {
            get {
                return ResourceManager.GetString("Reset_offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global hotkey to reset current temperature and brightness offset.
        /// </summary>
        public static string Reset_offset_ToolTip {
            get {
                return ResourceManager.GetString("Reset_offset_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set location.
        /// </summary>
        public static string Set_location {
            get {
                return ResourceManager.GetString("Set_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar configuration:.
        /// </summary>
        public static string Solar_configuration {
            get {
                return ResourceManager.GetString("Solar_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with Windows.
        /// </summary>
        public static string Start_with_Windows {
            get {
                return ResourceManager.GetString("Start_with_Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOP.
        /// </summary>
        public static string STOP {
            get {
                return ResourceManager.GetString("STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunrise.
        /// </summary>
        public static string Sunrise {
            get {
                return ResourceManager.GetString("Sunrise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunrise:.
        /// </summary>
        public static string Sunrise_colon {
            get {
                return ResourceManager.GetString("Sunrise_colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunrise transition starts at.
        /// </summary>
        public static string Sunrise_transition_starts_at {
            get {
                return ResourceManager.GetString("Sunrise_transition_starts_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunset.
        /// </summary>
        public static string Sunset {
            get {
                return ResourceManager.GetString("Sunset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunset:.
        /// </summary>
        public static string Sunset_colon {
            get {
                return ResourceManager.GetString("Sunset_colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunset transition starts at.
        /// </summary>
        public static string Sunset_transition_starts_at {
            get {
                return ResourceManager.GetString("Sunset_transition_starts_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature offset.
        /// </summary>
        public static string Temperature_offset {
            get {
                return ResourceManager.GetString("Temperature_offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature offset ↓.
        /// </summary>
        public static string Temperature_offset_down {
            get {
                return ResourceManager.GetString("Temperature_offset_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global hotkey to decrease current temperature offset.
        /// </summary>
        public static string Temperature_offset_down_ToolTip {
            get {
                return ResourceManager.GetString("Temperature_offset_down_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature offset ↑.
        /// </summary>
        public static string Temperature_offset_up {
            get {
                return ResourceManager.GetString("Temperature_offset_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global hotkey to increase current temperature offset.
        /// </summary>
        public static string Temperature_offset_up_ToolTip {
            get {
                return ResourceManager.GetString("Temperature_offset_up_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle LightBulb.
        /// </summary>
        public static string Toggle_LightBulb {
            get {
                return ResourceManager.GetString("Toggle_LightBulb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global hotkey to switch LightBulb on/off.
        /// </summary>
        public static string Toggle_LightBulb_ToolTip {
            get {
                return ResourceManager.GetString("Toggle_LightBulb_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition duration:.
        /// </summary>
        public static string Transition_duration {
            get {
                return ResourceManager.GetString("Transition_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration of time it takes to switch between day-time and night-time configurations.
        /// </summary>
        public static string Transition_duration_ToolTip {
            get {
                return ResourceManager.GetString("Transition_duration_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition offset:.
        /// </summary>
        public static string Transition_offset {
            get {
                return ResourceManager.GetString("Transition_offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset that specifies how early or late the transition starts relatively to sunrise and sunset.
        /// </summary>
        public static string Transition_offset_ToolTip {
            get {
                return ResourceManager.GetString("Transition_offset_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until sunrise.
        /// </summary>
        public static string Until_sunrise {
            get {
                return ResourceManager.GetString("Until_sunrise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your location:.
        /// </summary>
        public static string Your_location {
            get {
                return ResourceManager.GetString("Your_location", resourceCulture);
            }
        }
    }
}
